[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
JAVA_TOOL_OPTIONS = "-Xmx512m"
