server:
  port: ${PORT:8080}

# Application specific settings for Railway
app:
  upload-dir: ${UPLOAD_DIR:/tmp/uploads}
  frontend-url: ${FRONTEND_URL:https://zpluse.com}

spring:
  application:
    name: zplus-admin-panel
  
  datasource:
    # Railway provides DATABASE_URL automatically
    url: ${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://gondola.proxy.rlwy.net:51397/zplus_admin_panel}}
    driver-class-name: org.postgresql.Driver
    # Username and password are included in DATABASE_URL
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: false
    open-in-view: false
    defer-datasource-initialization: true

# Enable logging for debugging
logging:
  level:
    root: INFO
    '[com.zplus.adminpanel]': DEBUG
    '[org.springframework.security]': INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.jdbc]': DEBUG
    '[org.springframework.transaction]': DEBUG

# Simplified management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
