# Development Configuration for Z+ Admin Panel
spring:
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/zplus_admin_panel
    username: zplus_user
    password: zplus_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: false
        order_updates: false
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: adityamalik5763@gmail.com
    password: bsys ifpg gpof dfcm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  
# Application Configuration
app:
  mail:
    from: adityamalik5763@gmail.com
    admin-email: adityamalik5763@gmail.com
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: false
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

# Application Configuration
app:
  jwt:
    secret: ZplusAdminPanelSecretKeyForJWTTokenGeneration2024
    expiration: 86400000 # 24 hours
  upload:
    dir: ./uploads
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  security:
    password:
      encoder:
        strength: 10
    session:
      timeout: 7200 # 2 hours

# Logging Configuration
logging:
  level:
    root: INFO
    com.zplus.adminpanel: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/zplus-admin-panel-dev.log
    max-size: 5MB
    max-history: 7

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Cache Configuration
spring:
  cache:
    type: simple

# Actuator Configuration
management:
  health:
    db:
      enabled: true
    disk:
      enabled: true
    defaults:
      enabled: true 