server:
  port: ${PORT:8080}

# Application specific settings for Railway
app:
  upload-dir: ${UPLOAD_DIR:/tmp/uploads}
  frontend-url: ${FRONTEND_URL:https://zpluse.com}

spring:
  application:
    name: zplus-admin-panel
  
  datasource:
    # Use individual properties to avoid DATABASE_URL parsing issues
    url: jdbc:postgresql://gondola.proxy.rlwy.net:51397/railway
    username: postgres
    password: ocHfgptFatbBzfKxgNMmBMGQgZqIyGYc
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: false
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    defer-datasource-initialization: false
  
  sql:
    init:
      mode: always

# Enable logging for debugging
logging:
  level:
    root: INFO
    '[com.zplus.adminpanel]': DEBUG
    '[org.springframework.security]': INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.jdbc]': DEBUG
    '[org.springframework.transaction]': DEBUG

# Simplified management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
