# Alternative Railway Configuration with Multiple Database URL Formats

server:
  port: ${PORT:8080}

spring:
  application:
    name: zplus-admin-panel
  
  # Try multiple Railway PostgreSQL variable formats
  datasource:
    # Railway might provide different variable names
    url: ${DATABASE_URL:${POSTGRES_URL:${DB_URL:jdbc:postgresql://localhost:5432/zplus_db}}}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:${PGUSER:postgres}}
    password: ${POSTGRES_PASSWORD:${PGPASSWORD:password}}
    
    # Connection pool settings optimized for Railway
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Health check endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.zplus: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate.SQL: DEBUG
