server:
  port: 8080

spring:
  application:
    name: zplus-admin-panel
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/zplus_admin_panel
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # H2 Console (for development only)
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:adityamalik5763@gmail.com}
    password: ${MAIL_PASSWORD:bsys ifpg gpof dfcm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # FreeMarker Configuration
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

# JWT Configuration
jwt:
  secret: Bqe5Zevcwc4pCjuxviUf5bhHeYHVCbF9/pvgLM4vQ84=
  expiration: 86400000 # 24 hours

# Application Configuration
app:
  name: Z+ Admin Panel
  version: 1.0.0
  upload-dir: ${UPLOAD_DIR:./uploads}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  mail:
    from: ${MAIL_FROM:adityamalik5763@gmail.com}
    admin-email: ${ADMIN_EMAIL:adityamalik2206950100018@gmail.com}
  organization:
    name: Z+ Technologies
  
# Logging Configuration
logging:
  level:
    com.zplus.adminpanel: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:zplusdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    com.zplus.adminpanel: DEBUG
    org.springframework.security: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:zplus_admin_panel}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:zplus_user}
    password: ${DB_PASSWORD:zplus_password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.zplus.adminpanel: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  # JPA/Hibernate logging
  jpa:
    show-sql: true
