server:
  port: ${PORT:8080}

spring:
  application:
    name: zplus-admin-panel
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://gondola.proxy.rlwy.net:51397/zplus_admin_panel}
    driver-class-name: org.postgresql.Driver
    # Remove username/password - should be in DATABASE_URL
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Simplified management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.zplus: DEBUG
