-- Insert default admin user if not exists
INSERT INTO users (
    first_name, 
    last_name, 
    email, 
    phone, 
    department, 
    user_type, 
    project_id, 
    self_id, 
    password_hash, 
    reason, 
    supervisor, 
    status, 
    approved_by, 
    approved_at, 
    reference_id,
    is_active,
    username,
    position,
    profile_photo_url,
    rejection_reason,
    rejected_by,
    rejected_at,
    last_login,
    created_at,
    updated_at
) VALUES (
    'System',
    'Administrator',
    'adityamalik5763@gmail.com',
    '+1234567890',
    'IT Administration',
    'ADMIN',
    'ZP-2024-001',
    'ZP001',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: admin123
    'System administrator for Z+ Admin Panel',
    'System Owner',
    'APPROVED',
    'System',
    CURRENT_TIMESTAMP,
    'REF-ADMIN-001',
    TRUE,
    'admin',
    'System Administrator',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;
